# Root-Knot Nematode SSU rRNA phylogenetic analysis
# -------------------------------------------------
# control by editing the  config file

configfile: "config/config.yaml"

# samples to add to reference alignment, defined in config file
SAMPLES = config["seqs_to_add"]

# specify reference alignment in config
if config["clades123"]:
    REFERENCE = config["reference_alignment_clades123"]
else:
    REFERENCE = config["reference_alignment"]

# REF_FILTERED = config["filtered_ref_alignment"]
# REF_FILTERED = f"results/{config['reference_alignment']}_filtered.fas"

# output formats for trees, default is html (also png, pdf, svg)
TREEFORMATS = config.get("tree_formats", ["html"])

# -------------------------------
# include rule files
include: "rules/common.smk"
if config["add_sequences"]:
    include: "rules/qc.smk"
    include: "rules/alignment.smk"
    include: "rules/trees.smk"
    include: "rules/reports.smk"
else:
    include: "rules/reference.smk"
# -------------------------------

# The workflow is either adding sequences to the reference alignment,
# or just building a phylogeny of the reference alignment alone.
if config["add_sequences"]:
    rule all:
        input:
            # REF_FILTERED if config["exclude_seqs"] else REFERENCE,
            expand("results/samples/{sample}_validated.fas", sample=SAMPLES),
            "results/reporting/seqkit/initial_seqkit_report.md",
            expand("results/mafft/{sample}_mafft.fas", sample=SAMPLES),
            expand("results/reporting/mafft/{sample}_checkaddseqs_log.txt", sample=SAMPLES),
            expand("results/cialign/{sample}_mafft_cialign_cleaned.fasta", sample=SAMPLES),
            expand("results/reporting/plots/{sample}_length_histogram.html", sample=SAMPLES)
                if config.get("generate_seq_plots", False) else [],
            expand("results/reporting/plots/{sample}_alnseqlength_histogram.html", sample=SAMPLES)
                if config.get("generate_seq_plots", False) else [],
            expand("results/reporting/amas/{sample}_mafft_cialign_amas.tsv", sample=SAMPLES),
            expand("results/reporting/cialign/{sample}_mafft_cialign_output.png", sample=SAMPLES)
                if config.get("generate_seq_plots", False) else [],
            expand("results/iqtree/{sample}_mafft_cialign_cleaned_iqtree.treefile", sample=SAMPLES),
            expand("results/reporting/toytree/{sample}_mafft_cialign_cleaned_iqtree.{ext}", sample=SAMPLES, ext=TREEFORMATS),
else:
    rule all:
        input:
            expand("results/reference/{refalign}_iqtree.{ext}", refalign=get_ref_alignment_stub, ext=TREEFORMATS)
            # expand("results/reference/{refalign}_iqtree.html", refalign=REF)
