# ==================================================
#               RKN-rRNA: CONFIGFILE
# this file should be edited by the user to configure the analysis
# ==================================================
conda: "../envs/environment.yaml"  # leave this unedited

# reference alignment to which samples are added WITHOUT .fas file extension
reference_alignment: "7spp_new_142"

# add sequences to the reference alignment?
add_sequences: TRUE # FALSE will build a phylogeny of reference sequences only
ref_only: FALSE # TRUE if phylogeny of only reference alignment is required

# sequences to add
# give fasta "filename" in resources/samples/filename.fas WITHOUT the .fas extension
seqs_to_add: "Moleae"

# CIAlign
# list of sequences to keep whatever length filtering is done
retain_short_list: "config/retain_short_list.txt"
# minimum sequence length
cialign_minlen: "750"

# IQtree substitution model
subst_model: "GTR+R3" # Best-fit by BIC. GTR+I+G usually fine also.
