# ==================================================
#               RKN-rRNA: CONFIGFILE
# this file should be edited by the user to configure the analysis
# ==================================================
conda: "../envs/environment.yaml"  # leave this unedited

# reference alignment to which samples are added WITHOUT .fas file extension
reference_alignment: "clades123_7spp_new_142"

# add sequences to the reference alignment?
add_sequences: FALSE # FALSE will build a phylogeny of reference sequences only
ref_only: TRUE # TRUE if phylogeny of only reference alignment is required

# sequences to add
# give fasta "filename" in resources/samples/filename.fas WITHOUT the .fas extension
seqs_to_add: "7spp_new"

# # Remove seqs from the reference alignment TRUE/FALSE
# exclude_reference_seqs: FALSE
# # based on text file list of excluded seqs, 1 per line, fasta header line without >
# # can be used to remove deeper branching taxa for example
# exclusion_list_reference: "config/excluded_reference.txt"

# substitution model for IQtree
subst_model: "GTR+R3" # Best-fit model according to BIC. GTR+I+G fine also.

