name: rknrrna

channels:
  - conda-forge
  - bioconda

dependencies:
  - snakemake
  - python
  - snakefmt # re-format snakemake grammar
  - matplotlib
  - numpy<2.0 # CIalign needs older version
  - graphviz
  - pandas
  - altair
  - vl-convert-python # saving graphics formats
  - quarto # report building

  # sequences and general
  - biopython
  - seqkit # format conversion and stats reporting
  - csvtk # csv file toolkit, used in seqkit stats
  
  # alignments
  - mafft # mulitple sequence alignment
  - amas # alignment manipulation
  - cialign # alignment cleaning

  # trees
  - iqtree # tree construction
  - toytree # tree visualization
